/**
 * APCCI v1.1.0 — empirically calibrated anchors.
 *
 * v1.0.0 set its anchors from named episodes and approximate medians, so a
 * v1.0.0 reading of 60 did not mean "tighter than 60% of history" — it meant
 * "between two hand-picked reference points". v1.1.0 replaces the anchor
 * tables with the realised percentiles of each input over its full FRED
 * history, so a subscore of 60 means the reading sits at the 60th percentile
 * of that series' own history, and the index approximates the historical
 * percentile of credit conditions.
 *
 * The anchors are NOT written in this file. They are generated by
 * `node scripts/calibrate.mjs` into data/calibration/v1.1.0.json, which
 * records the percentiles together with the FRED vintage, observation counts
 * and a SHA-256 of every raw CSV the numbers came from. That artifact is the
 * calibration: it is committed, diffable, and re-derivable by anyone with FRED
 * access. This module only loads it.
 *
 * Until the artifact exists, v1.1.0 is defined but uncalibrated and computes
 * nothing. It never falls back to the v1.0.0 anchors: a value computed from
 * the wrong anchors under the 1.1.0 name would be exactly the "partial value
 * under the same name" the project forbids.
 */
import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const ARTIFACT_URL = new URL('../../../data/calibration/v1.1.0.json', import.meta.url);

/**
 * The canonical artifact location. APCCI_CALIBRATION overrides it so tests and
 * the synthetic demo can exercise a calibrated 1.1.0 without writing a
 * fabricated calibration to the real path. Production never sets it.
 */
export const ARTIFACT_PATH = process.env.APCCI_CALIBRATION
  ? process.env.APCCI_CALIBRATION
  : fileURLToPath(ARTIFACT_URL);

/**
 * Percentile grid used as the anchor knots. Dense in the tails because credit
 * spreads spend most of their time in a narrow band and the interesting
 * information is in the crisis tail.
 */
export const PERCENTILE_GRID = Object.freeze([0, 5, 25, 50, 75, 90, 95, 99, 100]);

/** Identical to v1.0.0. The calibration changes the anchors, not the mix. */
export const WEIGHTS = Object.freeze({
  hy_oas: 0.3,
  ccc_oas: 0.2,
  ig_oas: 0.2,
  nfci: 0.2,
  vix: 0.1,
});

let cache;

/** Reads the calibration artifact, or returns null when it has not been generated. */
export function loadCalibration({ force = false } = {}) {
  if (cache !== undefined && !force) return cache;
  if (!existsSync(ARTIFACT_PATH)) {
    cache = null;
    return cache;
  }
  const parsed = JSON.parse(readFileSync(ARTIFACT_PATH, 'utf8'));
  if (parsed.version !== '1.1.0') {
    throw new Error(
      `calibration artifact declares version ${parsed.version}, expected 1.1.0`,
    );
  }
  cache = parsed;
  return cache;
}

/** Builds the spec object. `anchors` is null when the artifact is absent. */
export function getSpec(opts) {
  const cal = loadCalibration(opts);
  if (!cal) {
    return Object.freeze({
      version: '1.1.0',
      status: 'pending_calibration',
      anchor_basis: 'empirical percentiles of full FRED history',
      calibrated: false,
      anchors: null,
      weights: WEIGHTS,
      percentile_grid: PERCENTILE_GRID,
      note:
        'Anchors have not been generated. Run `node scripts/calibrate.mjs` ' +
        'with FRED access (or `--from-dir <dir>` over downloaded CSVs) to ' +
        'produce data/calibration/v1.1.0.json. Until then v1.1.0 publishes nothing.',
    });
  }
  const anchors = Object.fromEntries(
    Object.entries(cal.series).map(([key, s]) => [key, s.anchors]),
  );
  return Object.freeze({
    version: '1.1.0',
    status: 'published',
    anchor_basis: 'empirical percentiles of full FRED history',
    calibrated: true,
    anchors,
    weights: WEIGHTS,
    percentile_grid: PERCENTILE_GRID,
    calibration: {
      vintage: cal.vintage,
      generated_at: cal.generated_at,
      method: cal.method,
      interpolation: cal.interpolation,
      series: Object.fromEntries(
        Object.entries(cal.series).map(([key, s]) => [
          key,
          { fred_id: s.fred_id, n: s.n, first_obs: s.first_obs, last_obs: s.last_obs, sha256: s.sha256 },
        ]),
      ),
    },
  });
}
