#!/usr/bin/env node
/**
 * Builds a SYNTHETIC demonstration of the full pipeline: generate inputs,
 * calibrate, publish both versions, render the site.
 *
 *   node scripts/demo.mjs
 *
 * WHY THIS EXISTS: the pipeline has to be exercisable end to end on a machine
 * with no FRED access, so that the code, the arithmetic and the page can be
 * checked before real data ever arrives.
 *
 * WHAT IT IS NOT: the index. The five series it writes are generated by a
 * seeded PRNG. They are not FRED data, not a reconstruction of FRED data, and
 * not an estimate of anything. Everything it produces is quarantined:
 *   - inputs   -> demo/raw/         (synthetic CSVs)
 *   - anchors  -> demo/calibration-SYNTHETIC.json (never data/calibration/)
 *   - values   -> demo/demo.db      (never data/apcci.db)
 *   - site     -> demo/site/        (never public/, and banner-warned)
 * Nothing under demo/ may ever be cited, and scripts/verify.mjs fails if a
 * synthetic artifact appears in a real location.
 */
import { mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { SERIES } from '../src/engine/series.js';

const root = fileURLToPath(new URL('..', import.meta.url));
const demo = join(root, 'demo');
const rawDir = join(demo, 'raw');
const calPath = join(demo, 'calibration-SYNTHETIC.json');
const dbPath = join(demo, 'demo.db');
const siteDir = join(demo, 'site');

rmSync(demo, { recursive: true, force: true });
mkdirSync(rawDir, { recursive: true });

/** Deterministic PRNG so the demo is byte-identical on every machine. */
function mulberry32(a) {
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}
const rand = mulberry32(20260725);
const gauss = () => {
  const u = Math.max(1e-9, rand()), v = rand();
  return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v);
};

// Business days from 1997 to the demo's end date.
const dates = [];
for (let t = Date.UTC(1997, 0, 2); t <= Date.UTC(2026, 6, 24); t += 86400000) {
  const d = new Date(t);
  const dow = d.getUTCDay();
  if (dow !== 0 && dow !== 6) dates.push(d.toISOString().slice(0, 10));
}

// A latent "stress" factor: mean-reverting, with a few synthetic episodes.
const episodes = [
  ['2001-03-01', 260, 1.5], ['2008-09-15', 300, 3.4], ['2011-08-01', 120, 1.2],
  ['2015-12-01', 150, 1.0], ['2020-02-24', 60, 3.0], ['2022-05-01', 200, 1.1],
];
const clamp = (x, lo, hi) => Math.min(hi, Math.max(lo, x));

// Episode start positions, resolved once (the date list is ~7,700 long).
const index = new Map(dates.map((d, i) => [d, i]));
const starts = episodes
  .map(([d, len, amp]) => [index.get(d) ?? -1, len, amp])
  .filter(([i]) => i >= 0);

// The transforms below are shaped so the series stay inside their plausible
// bounds without the clamps binding — a clamp that binds would pile probability
// mass on a single value and collapse the percentile anchors onto it.
// The episode term is an additive bump, not an accumulation. Adding it to z
// each day inside the window would drive z into its own ceiling within a week
// and hold it there, which shows up as long flat tops at exactly 100.
const bumpAt = (i) => {
  let b = 0;
  for (const [s, len, amp] of starts) {
    if (i >= s && i < s + len) {
      const phase = (i - s) / len;
      b += amp * Math.exp(-2.5 * phase) * Math.sin(Math.PI * Math.min(1, phase * 4));
    }
  }
  return b;
};

let ou = 0;
const rows = dates.map((date, i) => {
  ou = ou * 0.995 + gauss() * 0.05;
  // The ceiling sits well above the largest episode peak (~3.4) so it never
  // binds in practice; the exponents keep every series inside its plausible
  // range even at the ceiling, so the clamps below are a safety net, not a
  // shaper. Both matter: a binding clamp flattens the peaks into a plateau at
  // exactly 100 once the percentile anchors are fitted to the same sample.
  const z = clamp(ou + bumpAt(i), -0.55, 6);
  return {
    date,
    hy_oas: clamp(3.1 * Math.exp(0.3 * z) + gauss() * 0.05, 2.33, 21.8),
    ccc_oas: clamp(5.6 * Math.exp(0.33 * z) + gauss() * 0.12, 4.0, 43.9),
    ig_oas: clamp(1.0 * Math.exp(0.28 * z) + gauss() * 0.02, 0.51, 6.1),
    nfci: clamp(-0.55 + 0.63 * z + gauss() * 0.03, -1.0, 3.5),
    vix: clamp(15.5 * Math.exp(0.27 * z) + gauss() * 0.6, 9.2, 82.6),
  };
});

const NOTE = '# SYNTHETIC DATA - generated by scripts/demo.mjs - NOT FRED DATA';
for (const s of SERIES) {
  // NFCI is weekly in reality; emit Fridays only, as FRED does.
  const sel = s.key === 'nfci' ? rows.filter((r) => new Date(`${r.date}T00:00:00Z`).getUTCDay() === 5) : rows;
  const body = sel.map((r) => `${r.date},${r[s.key].toFixed(s.key === 'vix' ? 2 : 4)}`).join('\n');
  writeFileSync(join(rawDir, `${s.id}.csv`), `${NOTE}\nobservation_date,${s.id}\n${body}\n`);
  console.log(`  synthetic ${s.id.padEnd(14)} ${sel.length} rows`);
}

const run = (args, env = {}) => {
  const r = spawnSync(process.execPath, args, {
    cwd: root,
    stdio: 'inherit',
    env: { ...process.env, ...env },
  });
  if (r.status !== 0) process.exit(r.status ?? 1);
};

const withCal = { APCCI_CALIBRATION: calPath };
console.log('\n--- calibrate (synthetic) ---');
run(['scripts/calibrate.mjs', '--from-dir', rawDir, '--out', calPath, '--force'], withCal);
console.log('\n--- publish 1.0.0 ---');
run(['scripts/publish.mjs', '--version', '1.0.0', '--from-dir', rawDir, '--backfill', '--db', dbPath, '--quiet'], withCal);
console.log('\n--- publish 1.1.0 ---');
run(['scripts/publish.mjs', '--version', '1.1.0', '--from-dir', rawDir, '--backfill', '--db', dbPath, '--quiet'], withCal);
console.log('\n--- build site ---');
run(
  ['scripts/build-site.mjs', '--db', dbPath, '--out', siteDir, '--banner',
   '<strong>SYNTHETIC DEMONSTRATION — NOT THE PUBLISHED INDEX.</strong> Every number on this page ' +
   'was generated by a seeded random process in scripts/demo.mjs. It is not FRED data and must ' +
   'never be cited. It exists only to show that the pipeline and the arithmetic work.'],
  withCal,
);
console.log(`\nDemo site: ${join(siteDir, 'index.html')}`);
